#!/usr/bin/env python3
"""Batch 4: Translations for paragraph indices 600-937"""
import json

T = {
601: "Answer: B",
603: "Chỉ có VRRP là giao thức chuẩn mở (open standard protocol).",
605: "Tham khảo hình minh họa.",
607: "Một quản trị viên mạng cấu hình CPE để cung cấp quyền truy cập internet cho trụ sở công ty. Lưu lượng phải được cân bằng tải qua ISP1 và ISP2 để đảm bảo tính dự phòng. Hai tập lệnh nào phải được cấu hình trên router CPE? (Chọn hai)",
608: "A. ip route 0.0.0.0 0.0.0.0 198.51.100.1\nip route 0.0.0.0 0.0.0.0 203.0.113.1 2",
609: "B. ip route 0.0.0.0 128.0.0.0 198.51.100.1\nip route 128.0.0.0 128.0.0.0 203.0.113.1\nip route 0.0.0.0 0.0.0.0 198.51.100.1\nip route 0.0.0.0 0.0.0.0 203.0.113.1",
610: "C. ip route 0.0.0.0 128.0.0.0 198.51.100.1\nip route 128.0.0.0 128.0.0.0 203.0.113.1",
611: "D. ip route 0.0.0.0 0.0.0.0 198.51.100.1 255\nip route 0.0.0.0 0.0.0.0 203.0.113.1 255\nip route 128.0.0.0 128.0.0.0 203.0.113.1",
612: "E. ip route 0.0.0.0 0.0.0.0 198.51.100.1\nip route 0.0.0.0 0.0.0.0 203.0.113.1",
614: "Answer: B E",
616: "Đáp án A không đúng vì nó sử dụng tuyến tĩnh dự phòng (floating static route) với AD là 2 cho tuyến tĩnh thứ hai nên lưu lượng không thể cân bằng tải.",
617: "Administrative distance bằng 255 được coi là không thể truy cập, và các tuyến tĩnh có administrative distance bằng 255 không bao giờ được đưa vào bảng định tuyến -> Đáp án D không đúng.",
618: "Bây giờ hãy giải thích chi tiết hơn về lệnh \"ip route 128.0.0.0 128.0.0.0 …\". Nó giống như lệnh \"ip route 0.0.0.0 128.0.0.0 …\" hoặc chúng ta có thể gọi nó là tuyến \"0.0.0.0/1\". Vì quy tắc \"khớp tiền tố dài nhất\" (longest-prefix match), nó được ưu tiên hơn tuyến tĩnh mặc định \"0.0.0.0/0\". Vì vậy tuyến 0.0.0.0/0 sẽ không được sử dụng.",
619: "Bây giờ chúng ta có thể thấy tại sao đáp án C không đúng vì tuyến \"ip route 128.0.0.0 128.0.0.0 203.0.113.1\" luôn được ưu tiên hơn \"ip route 0.0.0.0 128.0.0.0 198.51.100.1\".",
620: "Đáp án B đúng vì chúng ta có hai tuyến \"0.0.0.0/1\" (\"0.0.0.0 128.0.0.0\" và \"128.0.0.0 128.0.0.0\" hoàn toàn giống nhau)",
622: "Tham khảo hình minh họa.",
631: "Một quản trị viên mạng đang cấu hình một router cho quyền truy cập của người dùng qua SSH. Lệnh service-password encryption đã được phát hành. Cấu hình phải đáp ứng các yêu cầu sau:",
632: "– Tạo tên người dùng là CCUser.\n– Tạo mật khẩu là NA!2$cc.\n– Mã hóa mật khẩu người dùng.",
633: "Cấu hình nào phải được thực hiện để đáp ứng các yêu cầu?",
634: "A. username CCUser password NA!2$cc\nenable password level 5 NA!2$cc",
635: "B. username CCUser privilege 15 password NA!2$cc\nenable secret 0 NA!2$cc",
636: "C. username CCUser secret NA!2$cc",
637: "D. username CCUser privilege 10 password NA!2$cc",
639: "Answer: C",
641: "Trên thực tế tất cả các đáp án khác trông cũng có vẻ tốt, nhưng đáp án C là lựa chọn tốt nhất vì mật khẩu của tên người dùng được mã hóa với mức bảo mật cao nhất.",
643: "Tham khảo hình minh họa.",
645: "Một kỹ sư phải cấu hình tuyến mạng tĩnh giữa hai mạng để máy chủ A giao tiếp với máy chủ B. Kéo và thả các lệnh từ bên trái vào các router mà chúng phải được cấu hình bên phải. Không phải tất cả các lệnh đều được sử dụng.",
653: "Tham khảo hình minh họa.",
662: "Subnet mask cho tuyến 172.16.4.0 là gì?",
665: "Answer: B",
667: "Giao diện (interface) hoặc cổng (port) nào trên WLC là mặc định cho việc quản trị thiết bị trong băng (in-band) và giao tiếp giữa bộ điều khiển và các access point?",
668: "A. virtual interface\nB. management interface\nC. console port\nD. service port",
670: "Answer: B",
672: "Management interface là giao diện mặc định cho việc quản lý trong băng (in-band) của bộ điều khiển và kết nối tới các dịch vụ doanh nghiệp như máy chủ AAA. Nó cũng được sử dụng cho giao tiếp giữa bộ điều khiển và các access point, cho tất cả CAPWAP hoặc lưu lượng thông điệp di động và đường hầm liên bộ điều khiển.",
673: "Reference: https://www.cisco.com/c/en/us/td/docs/wireless/controller/7-4/configuration/guides/consolidated/b_cg74_CONSOLIDATED/b_cg74_CONSOLIDATED_chapter_010011011.html",
675: "Tham khảo hình minh họa.",
677: "Địa chỉ IPv6 cho đoạn mạng LAN trên router R2 phải được cấu hình bằng định dạng EUI-64. Địa chỉ nào phải được sử dụng?",
678: "A. ipv6 address 2001:DB8:D8D2:1009:10A0:ABFF:FECC:1 eui-64\nB. ipv6 address 2001:DB8:D8D2:1009:12A0:AB34:FFCC:1 eui-64\nC. ipv6 address 2001:DB8:D8D2:1009:1230:ABFF:FECC:1 eui-64\nD. ipv6 address 2001:DB8:D8D2:1009:4345:80FF:FF16:7 eui-64",
680: "Answer: A",
682: "Trên giao diện LAN của R2, chúng ta sử dụng lệnh \"ipv6 address 2001:db8:d8d2:1009::/64 eui-64\" để yêu cầu router tự động gán địa chỉ IPv6 cho giao diện này. R2 lấy địa chỉ MAC của giao diện LAN là 12A0.ABDD.0002 và chèn FFFE vào giữa hai nửa này để tạo thành địa chỉ 64-bit 2001:DB8:D8D2:1009:12A0.ABFF:FEdd:0002.",
683: "Chúng ta phải đảo ngược cờ universal/local (U/L) (bit thứ 7) trong phần OUI của địa chỉ, vì vậy 12 (ở dạng hex) = 0001 0010 (ở dạng nhị phân) do đó sau khi lật bit thứ 7, chúng ta có 0001 0000 = 10 (ở dạng hex). Do đó, địa chỉ IPv6 EUI-64 sẽ là 2001:DB8:D8D2:1009:10A0:ABFF:FECC:1.",
684: "Lưu ý: Có một số tài liệu nói rằng chúng ta phải lật bit thứ 7 trong khi một số khác lại nói chúng ta phải thay đổi bit thứ 7 thành 1. Vì vậy chúng tôi đã thử nghiệm với IOSv15.4:",
686: "Chúng ta thấy địa chỉ MAC của E0/0 là \"aabb……..\" (\"a\" ở dạng hex = \"1010\") nên bit thứ 7 là 1. Khi chúng ta bật IPv6 trên giao diện này, địa chỉ link-local chuyển thành \"FE80::A8BB……..\". Vì vậy \"a\" đổi thành 8 (\"8\" ở dạng hex = 1000\") và chúng tôi chắc chắn rằng bit 1 đã đổi thành 0. Nhưng đây chỉ là địa chỉ link-local nên chúng tôi sẽ cố gắng gán một địa chỉ global unique:",
688: "Địa chỉ global unique được gán là \"2001::A8BB……..\" nên bit 1 cũng đổi thành 0.",
690: "Một công ty có mỗi văn phòng sử dụng truy cập không dây với nhiều SSID nhưng giới hạn khả năng chuyển vùng (roaming), bao phủ các vị trí khác nhau trên mạng LAN nội bộ của văn phòng, mạng khách, và quyền truy cập BYOD cho nhân viên. Thay đổi nào phải được bật để cải thiện trải nghiệm khách hàng trong quá trình thay đổi SSID?",
691: "A. Tối ưu hóa dự đoán chuyển vùng được hỗ trợ (Assisted Roaming Prediction Optimization)\nB. Chuyển đổi nhanh (Fast Transition)\nC. Danh sách láng giềng băng tần kép (Neighbor List Dual Band)\nD. Thay đổi SSID nhanh (Fast SSID Change)",
693: "Answer: D",
695: "\"Khi bạn bật Thay đổi SSID nhanh (Fast SSID Change), bộ điều khiển cho phép các client di chuyển giữa các SSID. Khi client gửi một yêu cầu liên kết mới cho một SSID khác, mục nhập client trong bảng kết nối của bộ điều khiển sẽ bị xóa trước khi client được thêm vào SSID mới.\"",
697: "Tham khảo hình minh họa.",
699: "EtherChannel được cấu hình với tốc độ (speed) 1000 và chế độ song công (duplex) là full ở cả hai đầu của channel group 1. Bước tiếp theo để cấu hình kênh trên switch A phản hồi với (nhưng không khởi tạo) giao tiếp LACP là gì?",
700: "A. interface range gigabitethernet0/0/0 -15\nchannel-group 1 mode desirable",
701: "B. interface range gigabitethernet0/0/0 -15\nchannel-group 1 mode on",
702: "C. interface port-channel 1\nchannel-group 1 mode auto",
703: "D. interface port-channel 1\nchannel-group 1 mode passive",
705: "Answer: D",
707: "Hai công nghệ VPN nào được Cisco khuyến nghị cho nhiều văn phòng chi nhánh và triển khai quy mô lớn? (Chọn hai)",
708: "A. IPsec remote access\nB. site-to-site VPN\nC. clientless VPN\nD. GETVPN\nE. DMVPN",
710: "Answer: D E",
712: "Cisco DMVPN có thể được triển khai cùng với Cisco IOS Firewall và Cisco IOS IPS, cũng như tính năng chất lượng dịch vụ (QoS), IP Multicast, split tunneling, và các cơ chế chuyển đổi dự phòng dựa trên định tuyến. Triển khai Cisco DMVPN quy mô lớn, tính khả dụng cao được thực hiện nhờ vào việc cân bằng tải qua nhiều hub Cisco DMVPN.",
713: "Reference: https://www.cisco.com/c/en/us/products/collateral/security/dynamic-multipoint-vpn-dmvpn/data_sheet_c78-468520.html",
714: "Get VPNs cung cấp khả năng bảo vệ truyền dẫn không đường hầm (tunnel free), phi kết nối (connectionless) quy mô lớn, tận dụng hạ tầng định tuyến hiện có và có thể được sử dụng với các mạng MPLS, IP, Frame relay và ATM.",
715: "Reference: https://ipwithease.com/flexvpn-vs-getvpn/",
717: "Site-to-Site VPN là một VPN đơn giản kết nối một site trung tâm và một site từ xa, hoặc một VPN hub-and-spoke kết nối một site trung tâm với nhiều site từ xa -> Nó không phù hợp cho các triển khai quy mô lớn.",
718: "Với clientless VPN, một đường hầm được thiết lập từ trình duyệt web trên thiết bị của người dùng từ xa đến giao diện bên ngoài của thành phần SSL của cổng VPN -> Nó không phù hợp cho các triển khai quy mô lớn.",
719: "IPSec remote access được sử dụng để kết nối các máy khách truy cập từ xa, chẳng hạn như PC hoặc thiết bị văn phòng nhỏ, văn phòng nhà (SOHO).",
721: "Tham khảo hình minh họa.",
736: "Có bao nhiêu mảng (array) hiện diện trong dữ liệu JSON?",
737: "A. một\nB. ba\nC. sáu\nD. chín",
739: "Answer: B",
741: "Mảng JSON (JSON array) được bao quanh bởi dấu ngoặc vuông [ ]. Trong câu hỏi này có tổng cộng ba dấu ngoặc vuông.",
743: "Tham khảo hình minh họa.",
768: "Một quản trị viên nhận được cuộc gọi từ một văn phòng chi nhánh về hiệu suất ứng dụng kém được lưu trữ tại trụ sở chính. Ethernet 1 được kết nối giữa Router1 và switch LAN. Điều gì xác định được sự cố?",
769: "A. Có sự không khớp về duplex.\nB. MTU không được đặt thành giá trị mặc định.\nC. Liên kết đang bị sử dụng quá mức (over utilized).\nD. Chính sách QoS đang loại bỏ lưu lượng.",
771: "Answer: A",
773: "Giao diện này gặp tình trạng collision cao (15000 collision) do đó một đầu có thể đang được cấu hình là \"Half-duplex\".",
775: "Tham khảo hình minh họa.",
785: "Một kỹ sư mạng cập nhật cấu hình hiện tại trên giao diện fastethernet1/1 switch SW1. Nó phải thiết lập một EtherChannel bằng cách sử dụng cùng một chỉ định nhóm với một switch của nhà cung cấp khác (vendor). Cấu hình nào phải được thực hiện để hoàn tất quá trình?",
786: "A. interface port-channel 2\nchannel-group 2 mode desirable",
787: "B. interface fastethernet 1/1\nchannel-group 2 mode on",
788: "C. interface port-channel 2\nchannel-group 2 mode auto",
789: "D. interface fastethernet 1/1\nchannel-group 2 mode active",
791: "Answer: D",
793: "PaGP là giao thức độc quyền của Cisco nên chúng ta phải chuyển sang LACP, một giao thức tiêu chuẩn mở.",
795: "Tham khảo hình minh họa.",
797: "Truy cập cục bộ cho R4 phải được thiết lập và phải đáp ứng các yêu cầu sau:\n– Chỉ cho phép truy cập Telnet.\n– Mật khẩu enable phải được lưu trữ an toàn.\n– Mật khẩu enable phải được áp dụng dưới dạng văn bản gốc (plain text).\n– Quyền truy cập đầy đủ vào R4 phải được cho phép khi đăng nhập thành công.",
798: "Script cấu hình nào đáp ứng được các yêu cầu?",
807: "A. Option A\nB. Option B\nC. Option C\nD. Option D",
808: "Answer: B",
810: "\"Chỉ cho phép truy cập Telnet\" -> Chỉ Option B và Option C là đúng.",
811: "Trên thực tế, lệnh \"login authentication\" trong Option C chỉ có thể được sử dụng khi AAA được bật (với lệnh \"aaa new-model\"). Và chúng ta không thể sử dụng \"login authentication\" mà không chỉ định danh sách xác thực:",
813: "Do đó chỉ còn Option B. Nhưng thực tế Option B không hoàn toàn đúng vì \"Quyền truy cập đầy đủ vào R4 phải được cho phép khi đăng nhập thành công\" nhưng trong option B chúng ta phải nhập mật khẩu bí mật (secret password) để có quyền truy cập đầy đủ vào R4 sau khi đăng nhập (với tên người dùng \"test1\" và mật khẩu \"testpass1\").",
815: "Một gói tin từ văn phòng chi nhánh của công ty có đích là host 172.31.0.1 tại trụ sở chính. Router gửi có ba kết quả khớp có thể có trong bảng định tuyến của nó cho gói tin: các tiền tố 172.31.0.0/16, 172.31.0.0/24, và 172.31.0.0/25. Router xử lý gói tin như thế nào?",
816: "A. Nó gửi lưu lượng qua tuyến mặc định 0.0.0.0/0.\nB. Nó gửi lưu lượng qua tiền tố 172.31.0.0/16.\nC. Nó gửi lưu lượng qua tiền tố 172.31.0.0/25.\nD. Nó gửi lưu lượng qua tiền tố 172.31.0.0/24.",
818: "Answer: C",
820: "Hành động nào phải được thực hiện khi tính năng bảo vệ bằng mật khẩu (password protection) được triển khai?",
821: "A. Lưu trữ mật khẩu như các liên hệ (contacts) trên thiết bị di động với xác thực một yếu tố.\nB. Chia sẻ mật khẩu với ban quản lý IT cấp cao để đảm bảo giám sát chặt chẽ.\nC. Bao gồm các ký tự đặc biệt và làm cho mật khẩu càng dài càng tốt.\nD. Sử dụng độ dài ít hơn tám ký tự khi mật khẩu phức tạp.",
823: "Answer: C",
825: "Khi một access point đang tìm cách gia nhập (join) vào một bộ điều khiển mạng WLAN, thông điệp nào được gửi đến giao diện AP-Manager?",
826: "A. DHCP request\nB. DHCP discover\nC. discovery response\nD. discovery request",
828: "Answer: D",
830: "Các LAP luôn kết nối với địa chỉ giao diện management của bộ điều khiển đầu tiên bằng một yêu cầu khám phá (discovery request). Bộ điều khiển sau đó thông báo cho LAP địa chỉ IP của giao diện Layer 3 AP-manager (có thể cũng là giao diện management theo mặc định) để LAP có thể gửi yêu cầu gia nhập (join request) đến giao diện AP-manager sau đó.",
831: "Reference: https://www.cisco.com/c/en/us/support/docs/wireless/5500-series-wireless-controllers/119286-lap-notjoin-wlc-tshoot.html",
833: "Lý do tại sao quản trị viên chọn triển khai phương pháp quản lý mạng tự động là gì?",
834: "A. Giảm thiểu sự không nhất quán trong cấu hình mạng.\nB. Tăng chi phí quản lý định kỳ.\nC. Cho phép cấu hình và triển khai \"box by box\" (từng thiết bị một).\nD. Giải mã các chính sách mật khẩu đơn giản.",
836: "Answer: A",
838: "Thiết bị nào phân chia mạng theo các miền bảo mật (security domain)?",
839: "A. access point\nB. firewall\nC. intrusion protection system\nD. wireless controller",
841: "Answer: B",
843: "Hai đặc điểm nào là đặc trưng của các máy ảo (virtual machines - VMs)? (Chọn hai)",
844: "A. Một VM trên một hypervisor tự động được kết nối với các VM khác.\nB. Một VM trên một hypervisor cá nhân chia sẻ tài nguyên một cách đồng đều.\nC. Hệ điều hành của mỗi VM phụ thuộc vào hypervisor của nó.\nD. Mỗi VM hoạt động độc lập với bất kỳ VM nào khác trong cùng một hypervisor.\nE. nhiều VM hoạt động trên cùng một phần cứng cơ bản (underlying hardware).",
846: "Answer: D E",
848: "Tham khảo hình minh họa.",
869: "Theo kết quả đầu ra, bộ tham số nào được xác thực bằng cách sử dụng bảng định tuyến của R7?",
870: "A. R7 thiếu gateway of last resort.\nR7 đang nhận các tuyến được phân phối lại (redistributed) từ BGP\nR7 sẽ chuyển tiếp lưu lượng định tuyến đến 10.90.8.0/24.",
871: "B. R7 thiếu gateway of last resort.\nR7 đang nhận các tuyến được phân phối lại (redistributed) trong EIGRP\nR7 sẽ chuyển tiếp lưu lượng định tuyến đến 10.90.8.0/24.",
872: "C. R7 có gateway of last resort khả dụng.\nR7 đang nhận các tuyến được phân phối lại từ BGP\nR7 sẽ loại bỏ (drop) lưu lượng định tuyến đến 10.90.8.0/24",
873: "D. R7 có gateway of last resort khả dụng.\nR7 đang nhận các tuyến được phân phối lại trong EIGRP\nR7 sẽ loại bỏ (drop) lưu lượng định tuyến đến 10.90.8.0/24.",
875: "Answer: D",
877: "Lưu lượng định hướng đến 10.90.8.0/24 khớp với dòng đầu ra \"10.90.0.0/16 [200/0] via 0.0.0.0, 03:57:59, Null0\" nên nó sẽ được chuyển tiếp đến giao diện Null0, đồng nghĩa với việc bị loại bỏ (dropped).",
878: "Từ ký tự \"D EX\", chúng ta biết rằng R7 đang nhận các tuyến được phân phối lại trong EIGRP (một giao thức định tuyến khác được phân phối lại vào EIGRP).",
880: "Tham khảo hình minh họa.",
891: "Một gói tin có nguồn từ 10.10.10.1 định tuyến đến 172.16.3.254. Subnet mask của tuyến đích là gì?",
894: "Answer: B",
896: "Gói tin định tuyến đến 172.16.3.254 sẽ được định tuyến thông qua mục nhập \"C 172.16.2.0/23 …\" vì mạng con này kéo dài từ 172.16.2.0 đến 172.16.3.255.",
898: "Chế độ hoạt động và vai trò của cổng dự phòng (backup port) trên một phân đoạn LAN chia sẻ trong Rapid PVST+ là gì?",
899: "A. chế độ blocking và cung cấp một đường đi thay thế hướng về bridge được chỉ định (designated bridge)\nB. chế độ listening và cung cấp một đường đi thay thế hướng về root bridge\nC. chế độ forwarding và cung cấp đường đi chi phí thấp nhất đến root bridge cho mỗi VLAN\nD. chế độ learning và cung cấp đường đi ngắn nhất hướng về root bridge xử lý lưu lượng ra khỏi mạng LAN",
901: "Answer: A",
903: "Cổng thay thế (alternate port) và cổng dự phòng (backup port) ở trạng thái chặn (blocking state) (hoặc trạng thái loại bỏ - discarding state) để ngăn chặn vòng lặp (loop).",
904: "Reference: https://www.ciscopress.com/articles/article.asp?p=2832407&seqNum=4",
907: "Hành vi chuyển tiếp từng bước (per-hop forwarding behavior) của DSCP nào được chia thành các phân lớp (subclass) dựa trên xác suất loại bỏ (drop probability)?",
908: "A. class-selector\nB. assured \nC. expedited\nD. default",
910: "Answer: B",
912: "Thuật ngữ Hành vi từng bước (Per-Hop Behaviour - PHB) đề cập đến cách một node sẽ xử lý lưu lượng có cùng giá trị Differentiated Services Code Point (DSCP).",
913: "Assured Forwarding có bốn lớp tiêu chuẩn từ AF1 đến AF4. Cần lưu ý rằng số thứ tự của lớp không quyết định mức độ ưu tiên. Mỗi lớp được xử lý độc lập và đưa vào các hàng đợi khác nhau.",
914: "Mỗi lớp AF có IP Precedence riêng với ba xác suất loại bỏ (drop probability): thấp (low), trung bình (medium) và cao (high).",
915: "Reference: https://www.routeprotocol.com/dscp-per-hop-behaviour-assured-forwarding/",
917: "Điều gì xảy ra khi switch nhận được một frame có đích đến là địa chỉ MAC không xác định (unknown MAC address)?",
918: "A. Frame được flood (tràn ngập) đến tất cả các giao diện trong VLAN mà frame đó thuộc về.\nB. Frame được flood đến tất cả các giao diện trong switch.\nC. Frame bị loại bỏ (discarded)\nD. Bảng địa chỉ MAC của switch bị xóa (flushed)",
920: "Answer: A",
922: "Kéo và thả các thông tin về các kiến trúc không dây từ bên trái vào các loại access point bên phải. Không phải tất cả các tùy chọn đều được sử dụng.",
926: "Cloud-Based Access Point\n+ được quản lý từ bảng điều khiển dựa trên Web (Web-based dashboard)\n+ hỗ trợ triển khai tự động (automatic deployment)",
927: "Lightweight Access Point\n+ được cấu hình và quản lý bởi một WLC\n+ hỗ trợ các chế độ hoạt động khác nhau (different operational modes)",
929: "Kiểm soát truy cập cuộc gọi (Call Admission Control) dựa trên SIP phải được cấu hình trong Cisco WLC GUI. Các cổng bắt lưu lượng SIP (SIP call-snooping) đã được cấu hình. Hai hành động nào phải được hoàn thành tiếp theo? (Chọn hai)",
930: "A. Đặt mức QoS thành silver hoặc cao hơn cho lưu lượng thoại (voice traffic)\nB. Bật Media Session Snooping trên WLAN\nC. Cấu hình hai vai trò QoS khác nhau cho dữ liệu (data) và thoại (voice)\nD. Đặt mức QoS thành platinum cho lưu lượng thoại\nE. Bật traffic shaping cho giao diện LAN của WLC",
932: "Answer: B D",
934: "Cấu hình SIP-Based CAC (CLI)\nThủ tục\nBước 1 Đặt thoại (voice) thành mức QoS platinum\nBước 2 Bật tính năng call-snooping cho một WLAN cụ thể\n…",
935: "Reference: https://www.cisco.com/c/en/us/td/docs/wireless/controller/8-10/config-guide/b_cg810/wireless_quality_of_service.html"
}

with open("part11_trans_batch4.json", "w", encoding="utf-8") as f:
    json.dump(T, f, ensure_ascii=False, indent=2)
print(f"Batch 4: {len(T)} translations saved")
