#!/usr/bin/env python3
"""Batch 1: Translations for paragraph indices 0-200"""
import json

# {paragraph_index: vietnamese_translation}
T = {
1: "Chức năng của northbound API trong kiến trúc mạng tách biệt tầng điều khiển (control) và tầng ứng dụng (application) là gì?",
2: "A. Nó nâng cấp phần mềm và khôi phục tập tin.\nB. Nó dựa vào việc cung cấp và cấu hình toàn cục.\nC. Nó hỗ trợ xử lý phân tán cho cấu hình.\nD. Nó cung cấp đường dẫn giữa bộ điều khiển SDN và các ứng dụng mạng.",
4: "Answer: D",
6: "Bây giờ, đến lượt các quản trị viên mạng và các ứng dụng SDN muốn điều khiển bộ điều khiển! Vì vậy bộ điều khiển cần một giao diện hướng bắc (northbound interface - NBI) để giao tiếp với chúng ta. Các ứng dụng NBI bao gồm nhiều dịch vụ mạng khác nhau, bao gồm ảo hóa mạng (network virtualization), cung cấp mạng ảo động (dynamic virtual network provisioning), giám sát tường lửa (firewall monitoring), quản lý danh tính người dùng (user identity management) và kiểm soát chính sách truy cập (access policy control).",
10: "Kéo và thả các lợi ích của kiến trúc không dây từ bên trái vào các loại kiến trúc tương ứng bên phải.",
14: "Split-MAC:\n+ Công việc được chia sẻ giữa access point và controller\n+ Các access point truyền beacon frame\n+ Sử dụng giao thức đường hầm CAPWAP (CAPWAP tunneling protocol)",
15: "Autonomous:\n+ Phù hợp cho môi trường doanh nghiệp nhỏ\n+ Hỗ trợ cấu hình và quản lý theo từng thiết bị",
17: "Một autonomous AP là thiết bị độc lập với cả phần cứng có dây và không dây để có thể kết nối (bridge) các máy khách không dây thuộc các SSID vào hạ tầng VLAN có dây. Mỗi autonomous AP phải được cấu hình với một địa chỉ IP quản lý để có thể truy cập từ xa bằng Telnet, SSH, hoặc giao diện web. Mỗi AP phải được quản lý và bảo trì riêng lẻ trừ khi bạn sử dụng nền tảng quản lý như Cisco DNA Center.",
18: "Sự phân chia công việc giữa WLC và LAP được gọi là kiến trúc split-MAC. LAP phải tương tác với các máy khách không dây ở mức thấp, được gọi là tầng điều khiển truy cập phương tiện (Media Access Control - MAC). Các chức năng này phải nằm trên phần cứng LAP, gần nhất với các máy khách. Các chức năng quản lý không phải là phần thiết yếu để xử lý frame mà là những thứ nên được quản trị tập trung. Do đó, các chức năng đó có thể được chuyển đến một nền tảng tập trung, cách xa AP.",
19: "Reference: https://www.ciscopress.com/articles/article.asp?p=2999384&seqNum=5",
21: "Kéo và thả các thuật ngữ Ansible từ bên trái sang bên phải.",
25: "+ tập hợp các hành động để thực hiện trên thiết bị đích, được viết ở định dạng YAML: playbook\n+ thiết bị đã cài đặt Ansible dùng để quản lý các thiết bị đích: control node\n+ thiết bị mạng, không cài đặt Ansible, có thể thực thi các lệnh trên đó: managed node\n+ hành động cụ thể cần thực hiện trên một hoặc nhiều thiết bị đích: task\n+ đơn vị mã Python được thực thi: module\n+ tập tin Ansible xác định các thiết bị đích để thực thi lệnh và tác vụ: inventory",
27: "Sau khi Ansible được cài đặt, nó tạo ra một số tập tin văn bản:",
28: "+ Playbooks: Các tập tin này cung cấp các hành động và logic về những gì Ansible nên làm. Ansible playbook là các tập tin chứa các tác vụ (task) để cấu hình máy chủ. Ansible playbook được viết ở định dạng YAML. Bên trong Playbook, chúng ta có:\n++ Module (còn được gọi là \"task plugin\" hoặc \"library plugin\") là các đơn vị mã riêng biệt có thể được sử dụng từ dòng lệnh hoặc trong một tác vụ playbook. Ansible thực thi mỗi module, thường trên managed node từ xa, và thu thập các giá trị trả về.\n++ Task: Task là đơn vị công việc nhỏ nhất của Ansible. Chúng là một chuỗi các hành động trên máy chủ đích, sử dụng các module để cung cấp chức năng.",
29: "Một task định nghĩa một hành động cần được thực hiện, trong khi module thực thi hành động đó trên managed host.",
30: "+ Inventory: là tập tin chứa danh sách các máy chủ (thường là địa chỉ IP, cổng) mà bạn muốn cấu hình hoặc quản lý. Các máy chủ trong inventory có thể được chia thành các nhóm nhỏ hơn để dễ quản lý và cấu hình. Mỗi nhóm có thể chạy các tác vụ khác nhau. Ví dụ về tác vụ là ping tất cả các máy chủ trong nhóm [routers].\n…",
33: "Control node là máy tính chạy Ansible. Managed node là bất kỳ thiết bị nào được quản lý bởi control node.\nReference: https://opensource.com/resources/what-ansible",
35: "Mục đích của traffic shaping là gì?",
36: "A. Nó cho phép nhận dạng luồng động.\nB. Nó cho phép định tuyến dựa trên chính sách (policy-based routing).\nC. Nó cung cấp dịch vụ nỗ lực tốt nhất (best-effort).\nD. Nó giới hạn việc sử dụng băng thông.",
38: "Answer: D",
40: "+ Shaping: giữ lại các gói tin dư thừa trong hàng đợi (queue) và sau đó lên lịch truyền phần dư thừa sau theo các khoảng thời gian. Khi lưu lượng đạt đến tốc độ tối đa đã cấu hình, các gói tin bổ sung được xếp hàng đợi thay vì bị loại bỏ để tiếp tục sau. Traffic shaping chỉ áp dụng trên các giao diện đầu ra (outbound) vì bộ đệm và xếp hàng chỉ xảy ra trên giao diện đầu ra. Shaping được cấu hình theo bit trên giây.",
41: "Dịch vụ Best Effort có nghĩa là dịch vụ trên mạng chia sẻ trong đó mạng không cung cấp bất kỳ đảm bảo nào rằng dữ liệu được gửi đến hoặc việc gửi đáp ứng bất kỳ chất lượng dịch vụ nào, có nghĩa là các dịch vụ nhận được tốc độ bit thay đổi không xác định, độ trễ và mất gói tin, tùy thuộc vào tải lưu lượng hiện tại -> Traffic shaping không loại bỏ gói tin nên nó không cung cấp dịch vụ best effort -> Đáp án C không đúng.",
42: "Lý do chính bạn sử dụng traffic shaping là để kiểm soát quyền truy cập vào băng thông khả dụng, để đảm bảo lưu lượng tuân thủ các chính sách đã thiết lập cho nó, và để điều tiết luồng lưu lượng nhằm tránh tắc nghẽn có thể xảy ra khi lưu lượng gửi vượt quá tốc độ truy cập của giao diện đích từ xa -> Đáp án D đúng.",
44: "Kéo và thả các đặc điểm của công nghệ quản lý thiết bị từ bên trái vào các loại triển khai tương ứng bên phải.",
48: "Cisco DNA Center\n+ điều phối cấu hình thiết bị nền\n+ hỗ trợ quản lý phần mềm tập trung\n+ hỗ trợ các API mở",
49: "Traditional\n+ dựa vào quản lý theo từng thiết bị\n+ cung cấp sự linh hoạt cao hơn cho các cấu hình tùy chỉnh và không chuẩn\n+ sử dụng quản lý phần mềm riêng lẻ",
51: "Loại cổng nào được sử dụng để kết nối với mạng có dây khi autonomous AP ánh xạ hai VLAN vào các WLAN của nó?",
52: "A. LAG\nB. EtherChannel\nC. trunk\nD. access",
54: "Answer: C",
56: "Trong ví dụ này, chúng ta sẽ cấu hình switch trong triển khai Autonomous AP. Đầu tiên, chúng ta cần tạo VLAN 21, được gán cho người dùng Corporate, và VLAN 22, được gán cho người dùng Guest. Sau đó chúng ta sẽ cấu hình giao diện trunk giữa AP và switch để cho phép nhiều VLAN đi qua liên kết.",
57: "Reference: https://study-ccna.com/autonomous-ap-access-point-configuration/",
59: "Tham khảo hình minh họa.",
60: "R1#show ip ospf interface g0/0/0",
61: "GigabitEthernet0/0/0 is up, line protocol is up",
62: "Internet address is 192.168.1.2/24, Area 0",
63: "Process ID 1, Router ID 192.168.1.2, Network Type POINT-TO-POINT, Cost: 1",
64: "Transmit Delay is 1 sec, State POINT-TO-POINT,",
65: "Timer intervals configured, Hello 15, Dead 20, Wait 20, Retransmit 5",
66: "Hello due in 00:00:08",
67: "Index 1/1, flood queue length 0",
68: "Next 0x0(0) /0x0(0)",
69: "Last flood scan length is 1, maximum is 1",
70: "Last flood scan time is 0 msec, maximum is 0 msec",
71: "Suppress hello for 0 neighbor(s)",
73: "R2#show ip ospf interface g0/0/0",
74: "GigabitEthernet0/0/0 is up, line protocol is up",
75: "Internet address is 192.168.1.1/24, Area 0",
76: "Process ID 1, Router ID 10.1.1.1, Network Type POINT-TO-POINT, Cost: 1",
77: "Transmit Delay is 1 sec, State POINT-TO-POINT,",
78: "Timer intervals configured, Hello 10, Dead 40, Wait 40, Retransmit 5",
79: "Hello due in 00:00:11",
80: "Index 1/1, flood queue length 0",
81: "Next 0x0(0)/0x0(0)",
82: "Last flood scan length is 1, maximum is 1",
83: "Last flood scan time is 0 msec, maximum is 0 msec",
84: "Suppress hello for 0 neighbor(s)",
85: "Kỹ sư mạng đang cấu hình router R2 làm router thay thế trên mạng. Sau khi áp dụng cấu hình ban đầu, người ta xác định rằng R2 không hiển thị R1 là neighbor. Cấu hình nào phải được áp dụng cho R2 để hoàn thành cấu hình OSPF và cho phép nó thiết lập quan hệ neighbor với R1?",
87: "R2(config)#interface g0/0/0\nR2(config-if)#ip ospf hello-interval 15\nR2(config-if)#ip ospf dead-interval 20",
89: "R2(config)#router ospf 1\nR2(config-router)#router-id 192.168.1.2",
91: "R2(config)#router ospf 1\nR2(config-router)#network 192.168.1.0255.255.255.0 area 2\nR2(config-router)#network 10.1.1.0 255.255.255.255 area 2",
93: "R2(config)#interface g0/0/0\nR2(config-if)#ip ospf dead-interval 20",
94: "A. Option A\nB. Option B\nC. Option C\nD. Option D",
96: "Answer: A",
98: "Để trở thành OSPF neighbor, các giá trị sau phải khớp trên cả hai router:",
99: "+ Area ID\n+ Authentication\n+ Hello and Dead Intervals\n+ Stub area Flag\n+ MTU Size",
101: "Đặc điểm của mô hình mạng collapsed-core là gì?",
102: "A. Nó cho phép tầng lõi (core) và tầng phân phối (distribution) hoạt động như một tầng kết hợp duy nhất.\nB. Nó cho phép tầng lõi và tầng truy cập kết nối với một thiết bị phân phối logic qua EtherChannel.\nC. Nó cho phép tất cả các máy trạm trong môi trường SOHO kết nối trên một switch duy nhất có truy cập internet.\nD. Nó cho phép các thiết bị không dây kết nối trực tiếp với tầng lõi, giúp truyền dữ liệu nhanh hơn.",
104: "Answer: A",
106: "Thiết kế phân cấp ba tầng tối đa hóa hiệu suất, khả dụng mạng và khả năng mở rộng thiết kế mạng. Hầu hết các campus doanh nghiệp nhỏ không phát triển đáng kể theo thời gian, và hầu hết các campus doanh nghiệp nhỏ đủ nhỏ để được phục vụ tốt bởi thiết kế phân cấp hai tầng, trong đó tầng lõi (core) và tầng phân phối (distribution) được gộp lại thành một tầng. Động lực chính cho thiết kế collapsed core là giảm chi phí mạng, trong khi vẫn giữ hầu hết các lợi ích của mô hình phân cấp ba tầng.",
107: "Reference: https://www.cisco.com/c/en/us/td/docs/solutions/Enterprise/Small_Enterprise_Design_Profile/SEDP/chap2.html",
109: "Mục đích của việc cấu hình các mức syslog khác nhau cho các thiết bị khác nhau trên mạng là gì?",
110: "A. để giới hạn tốc độ thông báo cho các mức nghiêm trọng khác nhau từ mỗi thiết bị\nB. để thiết lập mức nghiêm trọng (severity) của thông báo syslog từ mỗi thiết bị\nC. để xác định nguồn mà mỗi thông báo syslog bắt nguồn từ đó\nD. để kiểm soát số lượng thông báo syslog từ các thiết bị khác nhau được lưu trữ cục bộ",
112: "Answer: B",
114: "Câu hỏi này hơi khó hiểu. Nhưng câu hỏi muốn hỏi về mức nghiêm trọng (severity level) của thông báo syslog. Level = severity level.",
115: "Để giới hạn tốc độ thông báo (rate-limit messages - giới hạn số lượng gói syslog gửi đến syslog server), chúng ta sử dụng lệnh \"logging rate-limit …\" nên đáp án A không phải là đáp án tốt nhất cho câu hỏi này (mặc dù nó không hoàn toàn sai).",
117: "Giao diện nào cho phép giao tiếp giữa một chương trình trên controller và một chương trình trên các thiết bị mạng?",
118: "A. northbound interface\nB. software virtual interface\nC. southbound interface\nD. tunnel interface",
120: "Answer: C",
122: "Chúng ta sử dụng Southbound API để giao tiếp giữa các Controller và các Phần tử Mạng (Network Element).",
125: "Kéo và thả phương thức gọi REST API cho HTTP từ bên trái vào hành động tương ứng mà chúng thực hiện bên phải.",
129: "+ tạo tài nguyên trên server: POST\n+ đọc dữ liệu từ server: GET\n+ xóa tài nguyên khỏi server: DELETE\n+ cập nhật một mục trong cơ sở dữ liệu: PUT",
131: "GET: lấy dữ liệu\nPOST: tạo dữ liệu\nPUT: cập nhật toàn bộ (thay thế) một bản ghi hiện có\nPATCH: cập nhật một phần của bản ghi hiện có\nDELETE: xóa bản ghi",
132: "PUT tương tự POST ở chỗ nó có thể tạo tài nguyên, nhưng nó thực hiện điều đó khi có URL đã xác định, trong đó PUT thay thế toàn bộ tài nguyên nếu nó tồn tại hoặc tạo mới nếu nó không tồn tại.",
133: "Không giống PUT Request, PATCH thực hiện cập nhật một phần. Các trường cần được cập nhật bởi client, chỉ trường đó được cập nhật mà không sửa đổi các trường khác.",
135: "Mục đích chính của không gian địa chỉ riêng (private address space) là gì?",
136: "A. bảo tồn không gian địa chỉ duy nhất toàn cầu\nB. đơn giản hóa việc đánh địa chỉ trong mạng\nC. giới hạn số lượng node có thể truy cập qua Internet\nD. giảm độ phức tạp mạng",
138: "Answer: A",
140: "Lý do để cấu hình cổng trunk kết nối với cổng phân phối (distribution port) của WLC là gì?",
141: "A. Loại bỏ dự phòng khi có lỗi liên kết trong đường dữ liệu.\nB. Cho phép nhiều VLAN được sử dụng trong đường dữ liệu.\nC. Cung cấp dự phòng nếu có lỗi liên kết cho quản lý ngoài băng (out-of-band).\nD. Cho phép nhiều VLAN cung cấp quản lý ngoài băng (out-of-band).",
143: "Answer: B",
145: "Tham khảo hình minh họa.",
147: "Lưu lượng từ R1 đến mạng con 10.10.2.0/24 sử dụng 192.168.1.2 làm next hop. Một kỹ sư mạng muốn cập nhật cấu hình R1 sao cho lưu lượng có đích 10.10.2.1 đi qua router R3, và tất cả lưu lượng khác đến mạng con 10.10.2.0/24 đi qua R2. Lệnh nào phải được sử dụng?",
148: "A. ip route 10.10.2.1 255.255.255.255 192.168.1.4 115\nB. ip route 10.10.2.0 255.255.255.0 192.168.1.4 100\nC. ip route 10.10.2.0 255.255.255.0 192.168.1.4 115\nD. ip route 10.10.2.1 255.255.255.255 192.168.1.4 100",
150: "Answer: D",
152: "Mật mã (cipher) nào được hỗ trợ cho mã hóa không dây chỉ với chuẩn WPA2?",
155: "Answer: B",
157: "Không giống WEP và WPA, WPA2 sử dụng chuẩn AES thay vì mật mã dòng (stream cipher) Rivest Cipher 4 (RC4).",
158: "Chế độ WPA3-Enterprise sử dụng AES-256 ở chế độ GCM.",
159: "SHA là viết tắt của Secure Hash Algorithm trong khi AES là viết tắt của Advanced Encryption Standard. Vì vậy SHA là một bộ thuật toán băm (hashing algorithm). Nó không phải là mật mã (cipher) được sử dụng để mã hóa.",
161: "Tham khảo hình minh họa.",
162: "Entry #",
167: "Mục nào là kết quả khớp tiền tố dài nhất (longest prefix match) cho địa chỉ IP host 192.168.10.5?",
170: "Answer: B",
172: "Hai tính năng nào được giới thiệu trong SNMPv2 cung cấp khả năng lấy lượng lớn dữ liệu trong một yêu cầu? (Chọn hai)",
173: "A. Get\nB. GetNext\nC. Set\nD. GetBulk\nE. Inform",
175: "Answer: D E",
177: "Hai thông báo bổ sung được thêm vào trong SNMPv2 (so với SNMPv1)",
178: "GetBulkRequest - Thông báo GetBulkRequest cho phép SNMP manager truy cập các khối dữ liệu lớn. GetBulkRequest cho phép agent phản hồi với nhiều thông tin nhất có thể vừa trong PDU phản hồi. Các agent không thể cung cấp giá trị cho tất cả các biến trong danh sách sẽ gửi thông tin một phần.",
179: "InformRequest - Thông báo InformRequest cho phép các trạm NMS chia sẻ thông tin trap. (Trap được phát hành bởi các SNMP agent khi có thay đổi thiết bị.) Thông báo InformRequest thường được sử dụng giữa các trạm NMS, không phải giữa các trạm NMS và agent.",
181: "Tham khảo hình minh họa.",
182: "router# show ip route",
187: "C 172.18.32.32/32 is directly connected, Loopback0",
188: "C 172.18.32.36/30 directly connected, GigabitEthernet0/0",
189: "L 172.18.32.37/32 is directly connected, GigabitEthernet0/0",
190: "Một gói tin có nguồn từ 172.18.33.2 được gửi đến đích 172.18.32.38. Router chuyển tiếp gói tin đến đâu?",
193: "Answer: A",
195: "Mục nhập tốt nhất cho đích 172.18.32.38 là \"C 172.18.32.36/30 …, GigabitEthernet0/0\" nên router sẽ chuyển tiếp gói tin đến giao diện Gi0/0.",
197: "Tham khảo hình minh họa.",
199: "Bảng định tuyến của Router1 có nhiều phương thức để đến 10.10.10.0/24 như hình. Administrative Distance mặc định được sử dụng. Kéo và thả các điều kiện mạng từ bên trái vào các phương thức định tuyến mà Router1 sử dụng bên phải.",
}

with open("part11_trans_batch1.json", "w", encoding="utf-8") as f:
    json.dump(T, f, ensure_ascii=False, indent=2)
print(f"Batch 1: {len(T)} translations saved")
